In [4]:
import numpy as np

In [11]:
ints = np.ones(10, dtype = np.uint16)
floats = np.ones(10, dtype = np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [39]:
arr = np.arange(8)
arr
arr.reshape((4, 2)).reshape((2, 4))
arr.reshape((2, 2, -1))
#   参数可以有一个为-1，相当于自动推断
arr = np.arange(15).reshape((5, 3))
arr
t1 = arr.ravel()
t2 = arr.flatten()
t2[2] = 99
arr
t1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel()
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [60]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis = 1)
#   vstack => axis = 0, hstack => axis = 1
from numpy.random import randn
arr = randn(5, 2)
arr
first, second, third = np.split(arr, [1, 3])#   list的参数是左闭右开
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = randn(3, 2)
np.r_[arr1, arr2]
np.c_[np.r_[arr1, arr2], arr]
np.c_[1: 6, -10: -5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [72]:
arr = np.arange(3)
arr.repeat(3)
arr.repeat([2, 3, 4])
arr = randn(2, 2)
arr.repeat(2)#   没有设置轴向，数组将会扁平化
arr.repeat([2, 3], axis = 0)
arr
np.tile(arr, 2)#   水平方向
np.tile(arr, (4, 4))#   tuple说明了瓷砖的形状，每一块砖都是一个arr

array([[ 0.465868  , -1.46977035,  0.465868  , -1.46977035,  0.465868  ,
        -1.46977035,  0.465868  , -1.46977035],
       [ 0.20008968, -0.15160603,  0.20008968, -0.15160603,  0.20008968,
        -0.15160603,  0.20008968, -0.15160603],
       [ 0.465868  , -1.46977035,  0.465868  , -1.46977035,  0.465868  ,
        -1.46977035,  0.465868  , -1.46977035],
       [ 0.20008968, -0.15160603,  0.20008968, -0.15160603,  0.20008968,
        -0.15160603,  0.20008968, -0.15160603],
       [ 0.465868  , -1.46977035,  0.465868  , -1.46977035,  0.465868  ,
        -1.46977035,  0.465868  , -1.46977035],
       [ 0.20008968, -0.15160603,  0.20008968, -0.15160603,  0.20008968,
        -0.15160603,  0.20008968, -0.15160603],
       [ 0.465868  , -1.46977035,  0.465868  , -1.46977035,  0.465868  ,
        -1.46977035,  0.465868  , -1.46977035],
       [ 0.20008968, -0.15160603,  0.20008968, -0.15160603,  0.20008968,
        -0.15160603,  0.20008968, -0.15160603]])

In [87]:
arr = np.arange(10) * 100
arr
inds = [7, 1, 2, 6]
arr[inds]
arr.take(inds)
arr.put(inds, 99)
arr
arr.put(inds, [40, 41, 42, 43])
arr
inds = [2, 0, 2, 1]
arr = randn(2, 4)
arr
arr.take(inds, axis  = 1)
arr.put(inds, 99)#   只考虑行优先，没有轴的区别
arr

array([[ 9.90000000e+01,  9.90000000e+01,  9.90000000e+01,
        -6.77020591e-02],
       [ 1.67087848e-01,  4.25752564e-01,  3.55874648e-01,
         8.49233920e-01]])

In [101]:
#   广播指的是不同的数组之间的算术运算的执行方式
arr = np.arange(5)
arr * 4
arr = randn(4, 3)
arr.mean(0)
demeand = arr - arr.mean(0)
demeand.mean(0)
arr
row_means = arr.mean(1)
row_means.reshape((4, 1))
demeaned = arr - row_means.reshape((4, 1))

In [123]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape
arr_1d = np.random.normal(size = 3)
arr_1d[:, np.newaxis].shape
arr_1d[np.newaxis, :]
arr = np.arange(60).reshape((3, 4, 5))
depth_means = arr.mean(2)
depth_means[:, :, np.newaxis]

array([[[ 2.],
        [ 7.],
        [12.],
        [17.]],

       [[22.],
        [27.],
        [32.],
        [37.]],

       [[42.],
        [47.],
        [52.],
        [57.]]])

In [135]:
arr = np.zeros((4, 3))
arr[:] = 5
arr
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr
arr[: 2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [146]:
arr = np.arange(10)
np.add.reduce(arr)
arr.sum()
arr = randn(5, 5)
arr[::2].sort(1)
arr[:, :-1] < arr[:, 1:]
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis = 1)
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis = 1)#   部分和
np.add.reduce(arr, axis = 1)#   每一行加起来的最终和

array([10, 35, 60])

In [153]:
arr = np.arange(3).repeat([1, 2, 3])
arr
np.multiply.outer(arr, np.arange(5))
result = np.subtract.outer(randn(3, 4), randn(5))
result.shape
np.multiply.outer(arr, np.arange(5)).shape

(6, 5)

In [158]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])
#   [0: 5], [5: 8], [8: ]
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr
np.add.reduceat(arr, [0, 2, 4], axis = 1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

In [173]:
def add_elememt(x, y):
    return x + y
add_them = np.frompyfunc(add_elememt, 2, 1)
t1 = add_them(np.arange(8), np.arange(8))
add_them = np.vectorize(add_elememt, otypes = [np.float64])
t2 = add_them(np.arange(8), np.arange(8))
t1
t2
type(t1)
type(t2)

numpy.ndarray

In [178]:
dtype = [('x', np.float64), ('y', np.int32)]#   X字段和Y字段
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype = dtype)
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [188]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype = dtype)
arr[0]
arr[1]
arr[2]
arr[3]
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [195]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data  = np.array([((1, 2), 5), ((3, 4), 6)], dtype = dtype)
data['x']
data['y']
data['x']['a']

array([1., 3.])

In [200]:
arr = np.arange(10)
arr[2: 5] = 99
arr

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [208]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter
zip(last_name[sorter], first_name[sorter])

In [214]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind = 'mergesort')
indexer
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [224]:
data = np.floor(np.random.uniform(0, 10000, size = 50))
bins = np.array([0, 100, 1000, 5000, 10000])
data
labels = bins.searchsorted(data)
labels
from pandas import Series
Series(data).groupby(labels).mean()
np.digitize(data, bins)

array([4, 4, 4, 4, 2, 4, 3, 4, 4, 2, 4, 3, 3, 2, 3, 4, 4, 3, 4, 4, 3, 3,
       3, 4, 3, 2, 3, 2, 4, 3, 3, 4, 4, 3, 2, 3, 3, 3, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 2, 3])

In [225]:
#   切片可产生二维结果